//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpLists.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int ipId { get; set; }
        public string ip { get; set; }
        public string siteurl { get; set; }
    }
}
